gzhproperties:
  #  当前服务地址接收微信code地址
  servUrl: wx/callBack
  #  返回地址 具体业务地址.
  reUrl: 具体业务地址
  #  公众号id
  appId: 申请的公众号id
  #  公众号密钥
  appKey: 公众号密钥

#微信小程序参数
wxmpproperties:
  #  小程序认证id
  appId: 小程序id
  #  小程序密钥
  appkey: 小程序secret

#支付宝参数
zfbproperties:
  #  应用id
  appId: 支付宝应用id
  #  私钥
  priKey: 应用私钥
  #  支付宝公钥
  pubKey: 支付宝公钥
  #  加密方式
  signType: RSA2
  #  当前服务地址接收code地址
  servUrl: zfbwy/useCode

#  应用基础配置
appproperties:
#  http://公众号配置网址/本项目/
  url: 本项目所在域名/
  app: 本项目名/
  errKeyUrl: 没有参数时跳转地址
  errBrowserUrl: 提示微信支付宝跳转地址
#数据库连接参数
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: 具体的数据库
    username: 账户
    password: 密码

#mybatis配置
mybatis:
#  加载mapper文件地址
  mapper-locations: classpath*:mybatis/mapper/*Mapper.xml
  checkConfigLocation: false